# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
app_identifier("com.bksy.colormatch.app")
overwrite_screenshots(true)
username("thuyduong.ng0908@gmail.com")